#!/bin/tcsh
echo Test script started
sleep 1
echo Script run second = 1
sleep 1
echo Script run second = 2
sleep 1
echo Script run second = 3
sleep 1
echo Script run second = 4
sleep 1
echo Script run second = 5
sleep 1
echo Script run second = 6
sleep 1
echo Script run second = 7
sleep 1
echo Script run second = 8
sleep 1
echo Script run second = 9
sleep 1
echo Script run second = 10
echo Test script ending with status 0
exit 0
