# Default PyCue config file

# Logger
logger.format: "%(levelname)-9s %(module)-10s %(message)s"
logger.level: WARNING

# Cuebot Network Settings
cuebot.protocol: tcp
cuebot.grpc_port: 8443
cuebot.timeout: 10000
cuebot.max_message_bytes: 104857600
cuebot.exception_retries: 3

cuebot.facility_default: local
cuebot.facility:
    local:
        - localhost:8443
    dev:
        - cuetest02-vm.example.com:8443
    cloud:
        - cuebot1.example.com:8443
        - cuebot2.example.com:8443
        - cuebot3.example.com:8443

