# OpenCue SonarCloud pipeline

# No automated builds yet, against master or PRs.
trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud (OpenCue token)'
    organization: 'bcipriano'
    scannerMode: 'Other'

- task: SonarCloudAnalyze@1