# OpenCue SonarCloud pipeline

# No automated builds yet, against master or PRs.
trigger: none
pr: none

jobs:
- job: analyze
  displayName: Analyze with SonarCloud
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'SonarCloud (OpenCue token)'
      organization: 'bcipriano'
      scannerMode: 'Other'

  - task: SonarCloudAnalyze@1