# OpenCue SonarCloud pipeline

# No automated builds yet, against master or PRs.
trigger: none
pr: none

jobs:
- job: analyzePython
  displayName: Analyze Python Components
  pool:
    vmImage: 'ubuntu-16.04'
  container: opencuebuild/ci-opencue:2019
  steps:
  - bash: ci/python_coverage_report.sh
    name: coverageReport
    displayName: Generate Test Coverage Report
  - bash: |
      set -e

      SONAR_VERSION=4.0.0.1744

      wget -q https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONAR_VERSION}-linux.zip
      unzip -q sonar-scanner-cli-${SONAR_VERSION}-linux.zip

      # sonar-scanner by default reads most of its configuration from sonar-project.properties
      sonar-scanner-${SONAR_VERSION}-linux/bin/sonar-scanner -Dsonar.login=$(SONAR_TOKEN)
    name: analyzePython
    displayName: Analyze and Send to SonarCloud

- job: analyzeCuebot
  displayName: Analyze Cuebot
  pool:
    vmImage: 'ubuntu-16.04'
  container: opencuebuild/ci-opencue:2019
  steps:
  - bash: cd cuebot && ./gradlew jacocoTestReport sonarqube -Dsonar.login=$(SONAR_TOKEN)
    name: analyze
    displayName: Analyze and Send to SonarCloud
