# OpenCue SonarCloud pipeline

# No automated builds yet, against master or PRs.
trigger: none
pr: none

jobs:
- job: analyze
  displayName: Analyze with SonarCloud
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - bash: |
      set -e

      echo "fwihoij ${SONAR_TOKEN2} deijcjj"

      SONAR_VERSION=4.0.0.1744

      wget -q https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONAR_VERSION}-linux.zip
      unzip -q sonar-scanner-cli-${SONAR_VERSION}-linux.zip

      sonar-scanner-${SONAR_VERSION}-linux/bin/sonar-scanner -Dsonar.login=${SONAR_TOKEN2}
    name: analyzePython
    displayName: Analyze Python Components

  - bash: cd cuebot && ./gradlew sonarqube -Dsonar.login=${SONAR_TOKEN2}
    name: analyzeCuebot
    displayName: Analyze Cuebot


