# OpenCue SonarCloud pipeline

# No automated builds yet, against master or PRs.
trigger: none
pr: none

jobs:
- job: analyze
  displayName: Analyze with SonarCloud
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - bash: sonar-scanner -Dsonar.login=${SONAR_TOKEN}
    name: analyzePython
    displayName: Analyze Python Components

  - bash: cd cuebot && ./gradlew sonarqube -Dsonar.login=${SONAR_TOKEN}
    name: analyzeCuebot
    displayName: Analyze Cuebot
