# OpenCue SonarCloud pipeline

# No automated builds yet, against master or PRs.
trigger: none
pr: none

jobs:
- job: analyze
  displayName: Analyze with SonarCloud
  pool:
    vmImage: 'ubuntu-16.04'
  container: aswf/ci-base:2019.0
  steps:
  - bash: |
      set -e

      SONAR_VERSION=4.0.0.1744

      wget -q https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONAR_VERSION}-linux.zip
      unzip -q sonar-scanner-cli-${SONAR_VERSION}-linux.zip

      # Container user isn't allowed to install packages at system-level, so we use --user and
      # the custom path to the virtualenv script.
      pip install --user virtualenv
      ~/.local/bin/virtualenv venv
      source venv/bin/activate
      # Don't need --user here as we're now in the virtual environment.
      pip install -r requirements.txt

      coverage run --source=pycue/opencue/,pycue/FileSequence/ --omit=pycue/opencue/compiled_proto/* pycue/setup.py test
      PYTHONPATH=pycue coverage run -a --source=pyoutline/outline/ pyoutline/setup.py test
      coverage xml

      # sonar-scanner by default reads most of its configuration from sonar-project.properties
      sonar-scanner-${SONAR_VERSION}-linux/bin/sonar-scanner -Dsonar.login=$(SONAR_TOKEN)
    name: analyzePython
    displayName: Analyze Python Components

  - bash: cd cuebot && ./gradlew sonarqube -Dsonar.login=$(SONAR_TOKEN)
    name: analyzeCuebot
    displayName: Analyze Cuebot


