name: 'Build Python Packages'
runs:
  using: composite
  outputs:
    opencue_proto_path: ${{ steps.build_opencue_proto.outputs.opencue_proto_path }}
    opencue_pycue_path: ${{ steps.build_pycue.outputs.opencue_pycue_path }}
    opencue_pyoutline_path: ${{ steps.build_pyoutline.outputs.opencue_pyoutline_path }}
    opencue_cueadmin_path: ${{ steps.build_cueadmin.outputs.opencue_cueadmin_path }}
    opencue_cuesubmit_path: ${{ steps.build_cuesubmit.outputs.opencue_cuesubmit_path }}
    opencue_rqd_path: ${{ steps.build_rqd.outputs.opencue_rqd_path }}
  steps:
    - name: Prepare building packages
      shell: bash
      run: |
        pip install build

    - name: Build opencue_proto package
      shell: bash
      id: build_opencue_proto
      run: |
        python -m build --outdir packages ./proto
        echo "opencue_proto_path=$(ls ./packages/opencue_proto-*.whl)" >> $GITHUB_OUTPUT

    - name: Build opencue_pycue package
      shell: bash
      id: build_pycue
      run: |
        python -m build --outdir packages ./pycue
        echo "opencue_pycue_path=$(ls ./packages/opencue_pycue-*.whl)" >> $GITHUB_OUTPUT

    - name: Build opencue_pyoutline package
      shell: bash
      id: build_pyoutline
      run: |
        python -m build --outdir packages ./pyoutline
        echo "opencue_pyoutline_path=$(ls ./packages/opencue_pyoutline-*.whl)" >> $GITHUB_OUTPUT

    - name: Build opencue_cueadmin package
      shell: bash
      id: build_cueadmin
      run: |
        python -m build --outdir packages ./cueadmin
        echo "opencue_cueadmin_path=$(ls ./packages/opencue_cueadmin-*.whl)" >> $GITHUB_OUTPUT

    - name: Build opencue_cuesubmit package
      shell: bash
      id: build_cuesubmit
      run: |
        python -m build --outdir packages ./cuesubmit
        echo "opencue_cuesubmit_path=$(ls ./packages/opencue_cuesubmit-*.whl)" >> $GITHUB_OUTPUT

    - name: Build opencue_rqd package
      shell: bash
      id: build_rqd
      run: |
        python -m build --outdir packages ./rqd
        echo "opencue_rqd_path=$(ls ./packages/opencue_rqd-*.whl)" >> $GITHUB_OUTPUT

    - name: Upload opencue packages
      uses: actions/upload-artifact@v4
      with:
        name: opencue_packages
        path: packages
