# This file needs to be located here:
# /shots/spi/home/etc/cue3/default.yaml

# Cue3 library logger
logger.format: "%(levelname)-9s %(module)-10s %(message)s"
logger.level: WARNING

# Cuebot Network Settings
cuebot.port: 9019
cuebot.protocol: tcp
cuebot.grpc_port: 8443

# Ice Interfaces
cuebot.interface.whiteboard: WhiteboardStatic
cuebot.interface.admin: AdminStatic

cuebot.facility_default: lax
cuebot.facility:
    dev:
        - cue3test02-vm.spimageworks.com:9019
    lax:
        - localhost:9019
    maa:
        - cuebot1-vm.maa.spimageworks.com:9019
        - cuebot2-vm.maa.spimageworks.com:9019

cuebot.timeout: 10000
ice.init:
    Ice.ACM.Client: 60
    Ice.MessageSizeMax: 102400#
