#!/bin/bash
#
# tomcat        
#
# chkconfig: 345 98 02
# description: Start up the Cue3bot engine.
# processname: cue3
# Source function library.
. /etc/init.d/functions


RETVAL=0
WEBAPP_NAME=cue3
WEBAPP_USER=tomcat

#export JAVA_HOME=`cd /usr/java/jdk1.6; /bin/pwd`
export JAVA_HOME=`cd $(readlink -f /usr/bin/java | sed "s:bin/java::"); /bin/pwd`
export CATALINA_HOME=/opt/cue3
export CATALINA_PID=${CATALINA_HOME}/bin/catalina.pid

start() {

	echo -n $"Starting ${WEBAPP_NAME}"

	if [ -f /var/lock/subsys/${WEBAPP_NAME} ];
	then
		failure "/var/lock/subsys/${WEBAPP_NAME} check"
		echo
		return 1
	fi

	cd ${CATALINA_HOME}/bin
	/sbin/runuser ${WEBAPP_USER} -m -s /bin/bash -c "${CATALINA_HOME}/bin/catalina.sh start  >&/dev/null"
	RETVAL=$?
	if [ $RETVAL -gt 0 ];
	then
		failure "failed to start ${WEBAPP_NAME}"
		echo
		return
	fi
	
	[ $RETVAL -eq 0 ] && touch /var/lock/subsys/${WEBAPP_NAME} && success
	echo
}

stop() {

	if [ ! -f /var/lock/subsys/${WEBAPP_NAME} ];
	then
		warning
		echo "${WEBAPP_NAME} might not be running, killing anyway"
	fi

	echo -n $"Stopping ${WEBAPP_NAME}:"
	/sbin/runuser ${WEBAPP_USER} -m -s /bin/bash -c "${CATALINA_HOME}/bin/catalina.sh stop  >&/dev/null"
	RETVAL=$?
	[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/${WEBAPP_NAME} && rm -f ${CATALINA_PID}
	success
	echo
}

restart() {
	stop
	start
}

status() {

	if [ -f ${CATALINA_PID} ];
	then
		PID=`cat ${CATALINA_PID}`
		success
		echo "${WEBAPP_NAME} is running, pid ${PID}"
	else
		warning
		echo "${WEBAPP_NAME} is NOT running"
	fi
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		restart
		;;
	status)
		status
		;;
	*)
 		echo $"Usage: $0 {start|stop|restart|status}"
		exit 1
		
esac
exit $?
