kind: Deployment
apiVersion: apps/v1
metadata:
  name: opencue-rest-gateway
  namespace: opencue
  labels:
    app: opencue
    component: rest-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opencue
      component: rest-gateway
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: opencue
        component: rest-gateway
    spec:
      containers:
        - name: rest-gateway
          imagePullPolicy: Always
          terminationMessagePolicy: File
          ports:
            - containerPort: 8448
          image: docker-local.artifactory.spimageworks.com/gitlab/spi/dev/infrastructure/api/opencue/rest_gateway:latest
          env:
            - name: CUEBOT_ENDPOINT
              values: cuebot-grpc.opencue.svc.cluster.local:8443
          resources:
            limits:
              cpu: "1000m"
              memory: "2Gi"
            requests:
              cpu: "200m"
              memory: "1Gi"  
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: rest-gateway-service
  namespace: opencue
spec:
  selector:
    app: opencue
    component: rest-gateway
  ports:
    - protocol: TCP
      port: 8448
      targetPort: 8448