# Default pycue config file

# Logger
logger.format: "%(levelname)-9s %(module)-10s %(message)s"
logger.level: WARNING

# Cuebot Network Settings
cuebot.port: 9019
cuebot.protocol: tcp
cuebot.grpc_port: 8443
cuebot.timeout: 10000

cuebot.facility_default: lax
cuebot.facility:
    dev:
        - cue3test02-vm.spimageworks.com:9019
    lax:
        - cue3bot1.spimageworks.com:9019
        - cue3bot2.spimageworks.com:9019
        - cue3bot3.spimageworks.com:9019
    maa:
        - cuebot1-vm.maa.spimageworks.com:9019
        - cuebot2-vm.maa.spimageworks.com:9019

