
-- Create a table to keep track of arbitrary limits
CREATE TABLE "LIMIT" (
    "PK_LIMIT" VARCHAR2(36 BYTE) NOT NULL,
    "STR_NAME" VARCHAR2(255 BYTE) NOT NULL,
    "INT_MAX_VALUE" NUMBER(38,0) DEFAULT 0 NOT NULL
);

CREATE TABLE "LAYER_LIMIT" (
    "PK_LAYER_LIMIT" VARCHAR2(36 BYTE) NOT NULL,
    "PK_LAYER" VARCHAR2(36 BYTE) NOT NULL,
    "PK_LIMIT" VARCHAR2(36 BYTE) NOT NULL
);
