#!/usr/local/bin/perl

print "Test script started\n";
sleep 2;
print "test1\n";
sleep 2;
print "test2\n";
sleep 2;
print "test3\n";
sleep 2;
print "test4\n";
sleep 2;
print "test5\n";
print "Test script ending\n";

