#!/usr/local/bin/python

import sys
import getopt
import time

try:
    opts, argv = getopt.getopt(sys.argv[1:], 'ht:e:', [ 'help','timerun=',"exitstatus="])
except getopt.GetoptError:
    print "Command line option parse error"
    sys.exit(1)

timeRun = 10 # Seconds
exitStatus = 0

for o, a in opts:
    if o in ("-h", "--help"):
        print "Description:"
        print "  Simple test script for use with rqd development"
        print
        print "Syntax:"
        print "  -t <#>, --timerun <#>"
        print "  -e <#>, --exitstatus <#>"
        print
        print "Example:"
        print "  Run 1 minute, succeed:  test_script -t 60 -e 0"
        print "  Run 1 minute, fail:     test_script -t 60 -e 1"
        print "  Default:                test_script -t 10 -e 0"
        sys.exit(0)
    if o in ("-t", "--timerun"):
        timeRun = int(a)
    if o in ("-e", "--exitstatus"):
        exitStatus = int(a)
        
print "Test script started"

for second in range(1,timeRun+1):
    time.sleep(1)
    print "Script run second = %d" % second

print "Test script ending with status %d" % exitStatus
sys.exit(exitStatus)

