pipeline {
    agent any
    environment {
        BUILD_ID = sh(script: "TZ=utc git log -n 1 --pretty=format:'%cd.%h' --date=format-local:'%Y%m%d-%H%M%S'", returnStdout: true).trim()
    }
    stages {
        stage('Build') {
            steps {
                sh "docker build --target build -t opencue/cuebot-build:${env.BUILD_ID} -f cue3bot/Dockerfile ."
                sh "docker build --target build -t opencue/rqd-build:${env.BUILD_ID} -f rqd/Dockerfile ."
            }
        }
        stage('Test') {
            steps {
                sh "docker build --target test -t opencue/cuebot-test:${env.BUILD_ID} -f cue3bot/Dockerfile ."
                sh "docker build --target test -t opencue/rqd-test:${env.BUILD_ID} -f rqd/Dockerfile ."
            }
        }
        stage('Package') {
            steps {
                sh "docker build -t opencue/cuebot:${env.BUILD_ID} -f cue3bot/Dockerfile ."
                sh "docker build -t opencue/rqd:${env.BUILD_ID} -f rqd/Dockerfile ."
                sh "jenkins/extract_artifacts.sh ${env.BUILD_ID} ./build"
            }
        }
        stage('Publish') {
            steps {
                sh "jenkins/publish_artifacts.sh ${env.BUILD_ID} ./build"
            }
        }
    }
    post {
        always {
            archiveArtifacts artifacts: 'build/cuebot.jar', fingerprint: true
            archiveArtifacts artifacts: 'build/rqd-*.tar.gz', fingerprint: true
        }
    }
}
