pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'docker build --target build -t opencue/cuebot-build cue3bot/'
            }
        }
        stage('Test') {
            steps {
                sh 'docker build --target test -t opencue/cuebot-test cue3bot/'
            }
        }
    }
}
