# OpenCue testing pipeline

# Runs tests for all components.

# Trigger the pipeline on every commit to master. Pull Requests to any branch will trigger
# the pipeline as well, by default.
trigger:
- master

jobs:
- job: testPython2019
  displayName: Test Python Components (CY 2019)
  pool:
    vmImage: 'ubuntu-16.04'
  container: aswf/ci-opencue:2019.0
  steps:
  - bash: ci/run_python_tests.sh
    name: runTests
    displayName: Run Python Tests

- job: testPython2020
  displayName: Test Python Components (CY 2020)
  pool:
    vmImage: 'ubuntu-16.04'
  container: aswf/ci-opencue:2020
  steps:
  - bash: ci/run_python_tests.sh
    name: runTests
    displayName: Run Python Tests

- job: testCuebot2019
  displayName: Test Cuebot (CY 2019)
  pool:
    vmImage: 'ubuntu-16.04'
  container: aswf/ci-opencue:2019.0
  steps:
  - bash: cd cuebot && ./gradlew build --stacktrace
    name: test
    displayName: Build and Test Cuebot

- job: testCuebot2020
  displayName: Test Cuebot (CY 2020)
  pool:
    vmImage: 'ubuntu-16.04'
  container: aswf/ci-opencue:2020
  steps:
  - bash: cd cuebot && ./gradlew build --stacktrace
    name: test
    displayName: Build and Test Cuebot

- job: testSphinx2019
  displayName: Test docs build (CY 2019)
  pool:
    vmImage: 'ubuntu-16.04'
  container: aswf/ci-opencue:2019.0
  steps:
  - bash: ci/build_sphinx_docs.sh
    name: buildDocs
    displayName: Run sphinx build

- job: testSphinx2020
  displayName: Test docs build (CY 2020)
  pool:
    vmImage: 'ubuntu-16.04'
  container: aswf/ci-opencue:2020
  steps:
  - bash: ci/build_sphinx_docs.sh
    name: buildDocs
    displayName: Run sphinx build