global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: metrics
    static_configs:
      - targets:
          - 'metrics:8302'

  - job_name: db
    static_configs:
      - targets:
          - 'db-exporter:9187'
