{
 "title": "Cuebot",
 "description": "OpenCue Metrics for the Cue server",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "System calls",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cue_host_balance_success_total[1m])",
     "legendFormat": "balance success"
    },
    {
     "expr": "rate(cue_host_balance_failed_total[1m])",
     "legendFormat": "balance failed"
    },
    {
     "expr": "rate(cue_killed_offender_procs_total[1m])",
     "legendFormat": "killed offender procs"
    },
    {
     "expr": "rate(cue_killed_oom_procs_total[1m])",
     "legendFormat": "killed oom procs"
    },
    {
     "expr": "rate(cue_cleared_procs_total[1m])",
     "legendFormat": "cleared procs"
    },
    { "expr": "rate(cue_req_errors_total[1m])", "legendFormat": "req errors" }
   ]
  },
  {
   "title": "More System calls",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cue_booking_retries_total[1m])",
     "legendFormat": "booking retries"
    },
    {
     "expr": "rate(cue_booking_errors_total[1m])",
     "legendFormat": "booking errors"
    },
    {
     "expr": "rate(cue_booked_procs_total[1m])",
     "legendFormat": "booked procs"
    }
   ]
  },
  {
   "title": "Booking and Dispatch threads",
   "type": "graph",
   "description": "It has a total of 6, if it stays at 6 it's likely a host has deadlocked and will need to be found and killed.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cue_booking_threads_total", "legendFormat": "booking threads" },
    { "expr": "cue_dispatch_threads_total", "legendFormat": "dispatch threads" }
   ]
  },
  {
   "title": "Manage and Report threads",
   "type": "graph",
   "description": "It has a total of 6, if it stays at 6 it's likely a host has deadlocked and will need to be found and killed.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cue_manage_threads_total", "legendFormat": "manage threads" },
    { "expr": "cue_report_threads_total", "legendFormat": "report threads" }
   ]
  },
  {
   "title": "Booking over 1 min",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cue_booking_executed_total[1m])",
     "legendFormat": "executed"
    },
    {
     "expr": "rate(cue_dispatch_waiting_total[1m])",
     "legendFormat": "waiting"
    },
    {
     "expr": "rate(cue_dispatch_remaining_capacity_total[1m])",
     "legendFormat": "remaining capacity"
    },
    {
     "expr": "rate(cue_booking_rejected_total[1m])",
     "legendFormat": "rejected"
    }
   ]
  },
  {
   "title": "Manage over 1 min",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cue_manage_executed_total[1m])",
     "legendFormat": "executed"
    },
    {
     "expr": "rate(cue_manage_rejected_total[1m])",
     "legendFormat": "rejected"
    },
    {
     "expr": "rate(cue_manage_remaining_capacity_total[1m])",
     "legendFormat": "remaining capacity"
    },
    {
     "expr": "rate(cue_manage_waiting_total[1m])",
     "legendFormat": "waiting"
    }
   ]
  },
  {
   "title": "Dispatch over 1 min",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cue_dispatch_executed_total[1m])",
     "legendFormat": "executed"
    },
    {
     "expr": "rate(cue_dispatch_remaining_capacity_total[1m])",
     "legendFormat": "remaining capacity"
    },
    {
     "expr": "rate(cue_dispatch_waiting_total[1m])",
     "legendFormat": "waiting"
    },
    {
     "expr": "rate(cue_dispatch_rejected_total[1m])",
     "legendFormat": "rejected"
    }
   ]
  },
  {
   "title": "Report over 1 min",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cue_report_executed_total[1m])",
     "legendFormat": "executed"
    },
    {
     "expr": "rate(cue_report_rejected_total[1m])",
     "legendFormat": "rejected"
    },
    {
     "expr": "rate(cue_report_remaining_capacity_total[1m])",
     "legendFormat": "remaining capacity"
    },
    {
     "expr": "rate(cue_report_waiting_total[1m])",
     "legendFormat": "waiting"
    }
   ]
  }
 ]
}