# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: OpenCue Testing Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_python_2019:
    runs-on: ubuntu-latest
    container: aswf/ci-opencue:2019.0
    steps:
      - uses: actions/checkout@v2
      - name: Run Python Tests
        run: ci/run_python_tests.sh

  build_cuebot_nodocker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build with Gradle
        run: cd cuebot && ./gradlew build --stacktrace

  build_cuebot_2019:
    runs-on: ubuntu-latest
    container: aswf/ci-opencue:2019.0
    steps:
    - uses: actions/checkout@v2
    - name: Build with Gradle
      run: cd cuebot && ./gradlew build --stacktrace
