name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Install X11 dev libs
        run: |
          sudo apt-get update && sudo apt-get install -y libx11-dev protobuf-compiler
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rust-install.sh
          bash ./rust-install.sh -y
      - name: Build
        run: |
          cd rust
          cargo build --release --verbose
      - name: Run tests
        run: |
          cd rust
          cargo test --verbose

  clippy:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Install X11 dev libs
        run: |
          sudo apt-get update && sudo apt-get install -y libx11-dev protobuf-compiler
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rust-install.sh
          bash ./rust-install.sh -y
      - name: Run Clippy
        run: |
          cd rust
          cargo clippy --verbose
