name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install X11 dev libs
        run: |
          sudo apt-get update && sudo apt-get install -y libx11-dev
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - name: Build
        run: |
          cd rust
          cargo build --release --verbose
      - name: Run tests
        run: |
          cd rust
          cargo test --verbose

  clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install X11 dev libs
        run: |
          sudo apt-get update && sudo apt-get install -y libx11-dev
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - name: Run Clippy
        run: |
          cd rust
          cargo clippy --verbose
