name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Install X11 dev libs
        run: |
          sudo apt-get update && sudo apt-get install -y libx11-dev protobuf-compiler
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rust-install.sh
          bash ./rust-install.sh -y
      - name: Build
        run: |
          cd rust
          cargo build --release --verbose
      - name: Run tests
        run: |
          cd rust
          cargo test --verbose

  clippy:
    runs-on: ubuntu-22.04

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Install X11 dev libs
        run: |
          sudo apt-get update && sudo apt-get install -y libx11-dev protobuf-compiler
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rust-install.sh
          bash ./rust-install.sh -y
      - name: Run Clippy
        run: |
          cd rust
          cargo clippy --verbose
