name: (TEMP) Build Docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_image:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Fetch all Git history, otherwise the current version number will
          # not be correctly calculated.
          fetch-depth: 0

      - name: Set build ID
        run: |
          set -e
          echo -n "0.21.22" > VERSION
          echo "Build ID: $(cat ./VERSION)"
          echo "BUILD_ID=$(cat ./VERSION)" >> ${GITHUB_ENV}

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          file: pyoutline/Dockerfile
          tags: opencuebuild/pyoutline:${{ env.BUILD_ID }}
          push: false
